### ISSUE TITLE
Support for public/shared for package in manifest.yml

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-runtime#132]
## Feature request parity with wskdeploy

wskdeploy supports shared package definitions via:
```
packages:
  my-package:
    public: true
    [...]
```
see https://github.com/apache/openwhisk-wskdeploy/issues/621 for more details

## Current workaround
deploy package and do `aio runtime package update my-package --shared true `
