### ISSUE TITLE
CLI tool is not replacing '$' placeholders with environment variables

### ISSUE THREAD

**Issue by ekremney** [adobe/aio-cli-plugin-runtime#145]
**Describe the bug**
CLI tool is not replacing '$' placeholders (indented more than one level) with environment variables.
 
**To Reproduce**
Example manifest file:
```yml
packages:
  __APP_PACKAGE__:
    version: 1.0.0
    license:  Adobe-2006
    actions:
      someAction:
        function: dist/someAction
        runtime: nodejs:10
        web-export: true
        annotations:
          final: true
        inputs:
          eventingConnection:
            bootstrapServers: $BOOTSTRAP_SERVERS
            saslUsername: $SASL_USERNAME
```

**Expected behavior**
I expect aio cli tool to replace $ placeholders with environment variables regardless of the indentation level.

**Additional context**
An example error:
```
Error: Error connecting to the host: $BOOTSTRAP_SERVERS failed - getaddrinfo ENOTFOUND
```

**Comment by shazron** [comment]
I'm not sure this is valid input. 

According to the spec, an `action` takes an optional `inputs` key, which is a list of `parameter`s: https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_actions.md#actions

`parameter`s are specified as: https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_parameters.md

in the `parameters` spec above, there is a  key called `properties` that takes in a list of parameters, but that's different than your case.

It's possible that the spec hasn't been updated, but the tests have been (I encountered this for https://github.com/adobe/aio-cli-plugin-runtime/pull/138#issuecomment-609721659). 

However, I went through all the test fixtures in https://github.com/apache/openwhisk-wskdeploy none of them had the scenario you had, which makes me believe it is not supported.

**Comment by tysonnorris** [comment]
does structuring inputs like:
```
        inputs:
          bootstrapServers: $BOOTSTRAP_SERVERS
          saslUsername: $SASL_USERNAME
```
work?

**Comment by moritzraho** [comment]
@tysonnorris yes if this is supported, $<VAR> being an env variable.
What's not supported, what the issue mentions, is multi level inputs with env vars

**Comment by moritzraho** [comment]
@shazron in that case should we mark this as an enhancement instead of a bug?
As the openwhisk api seem to support multi level input objects, it would be nice if we would too?

**Comment by shazron** [comment]
Since we are currently following the `wskdeploy` manifest format spec, adding this enhancement will break compatibility. We need to decide if compatibility is paramount for our manifest, and to weigh that with any future breaking enhancements.

**Comment by meryllblanchet** [comment]
Compatibility is as of today a paramount for our manifest and I'm not in favor of deviating from the original specifications unless there's a very good reason and benefit or our end-users.

I propose then to close the issue for the time being and reevaluate if we see this as a recurring need.

**Comment by meryllblanchet** [comment]
Reopening as @ekremney has some more information to provide

**Comment by ekremney** [comment]
According to the [specification](https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_parameter_types.md#openwhisk-types), parameter types include `object` which is defined as:

> The parameter itself is an object with the associated defined Parameters (schemas).

Object type is explained [at the bottom of the page](https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_parameter_types.md#object-type-example)

> The Object type allows for complex objects to be declared as parameters with an optional validatable schema.

As a developer who uses Openwhisk, I would like to be able to group my parameters so that I can address them differently in my code. It especially comes very handy if you use openwhisk wrappers. Ie:

```yml
inputs:
  logging:
    host: <host>
    token: <token>
    index: <index>
  service:
    host: <host>
    token: <token>
...
```

Then you can just initialize your wrappers:
```js
...
new LoggingWrapper(params.logging);
...
```



FYI, we are migrating from `wskdeploy` to `aio`. `wskdeploy` tool injects ENV variables into nested parameters.

@meryllblanchet @tysonnorris @shazron

**Comment by solaris007** [comment]
Also, `wskdeploy` features sample multi-level config and associated test:

multi-level inputs test file: https://github.com/apache/openwhisk-wskdeploy/blob/master/tests/dat/manifest_validate_multiline_params.yaml

and the test case:
https://github.com/apache/openwhisk-wskdeploy/blob/db5e34e35825900c52017b545e56935c5bea5578/parsers/manifest_parser_test.go#L288

I kindly ask you to add feature parity with wskdeploy in this case. single-level configurations are super ugly and unreadable.

**Comment by shazron** [comment]
Thanks @ekremney, it is clear now. I didn't see this file. I'll send a PR to the `spec_parameters.md` doc to link the docs to the type schema at `spec_parameter_types.md`.

There doesn't seem to be any test fixtures in `wskdeploy` that test inputs with object types (as I mentioned in a previous comment, all are type string), so I'm surprised it works with wskdeploy (probably just an omission in the tests).

**Comment by shazron** [comment]
PR filed: https://github.com/apache/openwhisk-wskdeploy/pull/1094

**Comment by shazron** [comment]
@solaris007 I don't think there is any question that we will try to achieve parity with wskdeploy, we were trying to determine if it is in the spec, which it has been clarified that it is.

With regards to the test you mentioned, that is for type `json`, which is entirely different than type `object`. There is no test for `object` in that file, thus no test for "nested objects" (the file tests multi-line params).

**Comment by alexkli** [comment]
Why not simply replace env vars in all of the manifest.yml in a first pass after loading it? Makes the code simpler and it works everywhere. If done right you can also do arrays etc. in the replacement.

I don’t know if that will create a conflict with the wskdeploy spec but aio is different already.

Here is my workaround for that using npm scripts:

In package.json:

```
  "scripts": {
    "deploy": "aio app deploy",
    "predeploy": "cp manifest.yml manifest.backup.yml; envsub -f .env -s dollar-basic manifest.yml",
    "postdeploy": "mv manifest.backup.yml manifest.yml"
  }
```

Then run `npm run deploy` to invoke `aio app deploy`. to pass arguments to aio app deploy, run e.g. `npm run deploy -- --skip-static`.

Note it is slightly dangerous since if deploy fails then it will not run postdeploy and restore the original manifest. So you might have a modified manifest with e.g. credentials present, and could mistakenly commit them. So watch out.

**Comment by ekremney** [comment]
Hi @alexkli,

This issue just pinpoints the discrepancy between `wskdeploy` and `aio`. `wskdeploy` supports `object` type parameters whereas `aio` does not.

That's a nice workaround you mention. In fact, we used `envsubst` for a while, then we decide to use yaml anchors to group input parameters so that we won't have to repeat inputs for each action while keeping them top-level (for `aio` to work well). For example:

```yaml
inputs:
  auth: &auth
    public-key: $PUBLIC_KEY
  db: &db
    host: $DB_HOST
    password: $DB_PASS
  logging: &logging
    host: $LOGGING_HOST
    token: $LOGGING_TOKEN

packages:
  __APP_PACKAGE__:
  actions:
    login:
      function: actions/login
      inputs:
        <<: *auth
        <<: *logging
    getSomething:
      function: actions/getSomething
      inputs:
        <<: *db
        <<: *logging
    doSomething:
      function: actions/doSomething
      inputs:
        <<: *logging
```
