### ISSUE TITLE
`require-adobe-auth` sequence is not handling user defined web annotations

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-runtime#150]
**Describe the bug**

consider the following manifest:

```
packages:
 the-pkg:
    license: Apache-2.0
    actions:
      analytics:
        function: actions/analytics/index.js
        web: 'yes'
        runtime: 'nodejs:10'
        inputs:
          LOG_LEVEL: debug
          companyId: $ANALYTICS_COMPANY_ID
          apiKey: $ANALYTICS_API_KEY
        annotations:
          require-adobe-auth: true
          final: true
```

Here the `final` annotation will not be taken into account by the generated web sequence, this also applies to the `web-custom-options` annotation, and potentially other web action annotations: see https://github.com/apache/openwhisk/blob/master/docs/annotations.md#annotations-specific-to-web-actions

Here is the current implementation of the generated web sequence
https://github.com/adobe/aio-cli-plugin-runtime/blob/master/src/runtime-helpers.js#L492.

Setting the user defined web annotations to the generated web sequence would fix the missing support for the `web-custom-options`, however the final annotation is not supported by sequences in OpenWhisk, see https://github.com/apache/openwhisk/issues/3392. 

And because the user action in the sequence is secured by making it non web, the final annotation, which is reserved for web actions, doesn't work on the underlying action neither.

Some options to support the final annotation:
1. we add support for the final annotation for web sequences in OpenWhisk
2. we find a solution at cli level (client side), for example:
  - make user action web again and secure it with `require-whisk-auth:<USER_OW_AUTH>`
  - generate a single web action that embeds the code of the validator and user action
3. wait for Adobe I/O Runtime support of the annotation at GW level
