### ISSUE TITLE
export command is failing

### ISSUE THREAD

**Issue by Himavanth** [adobe/aio-cli-plugin-runtime#171]
**Describe the bug**
`aio runtime deploy export` command fails.

**To Reproduce**
```
project:
  name: expproj
  packages:
    mypackage:
      public: true
```
With the above manifest, execute `aio runtime deploy sync` first 
and then `aio runtime deploy export -m exp_man.yml --projectname expproj`

This is failing because `aio runtime deploy sync` no longer adds package annotations now and so `export` fails when it looks for the annotation.

**Expected behavior**
should export to given manifest

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
