### ISSUE TITLE
export command produces manifest in different format and breaks the app commands

### ISSUE THREAD

**Issue by Himavanth** [adobe/aio-cli-plugin-runtime#174]
**Describe the bug**
With `aio rt export` the manifest we get looks like below.
```
project:
  name: expproj
  packages:
    __APP_PACKAGE__:
```
Trying any of the app commands eg: `aio app logs` with this exported manifest fails with 
```
TypeError: Cannot read property '__APP_PACKAGE__' of undefined
```
This is because app plugin expects the manifest format like below
```
project:
  name: expproj
packages:
  __APP_PACKAGE__:
```
Notice that `packages` is at the same level as `project`

**To Reproduce**
See above

**Expected behavior**
Should work

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
