### ISSUE TITLE
Support default params for packages in app manifest

### ISSUE THREAD

**Issue by duynguyen** [adobe/aio-cli-plugin-runtime#200]
**Is your feature request related to a problem? Please describe.**
With the `aio runtime` CLI plugin, you can set default params for package, e.g.
```
aio rt package create sample-app-0.0.1 --param city NYC --param country USA
```
However it doesn’t seem possible in `wskdeploy`: https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_packages.md#packages
Because the manifest spec of Firefly follows `wskdeploy` convention, it doesn't support this use case as well

**Describe the solution you'd like**
It should be possible to set default params for packages. Example snippet below.

```yaml
packages:
  __APP_PACKAGE__:
    license: Apache-2.0
    inputs:
      city: $CITY
      country: $COUNTRY
    actions:
      ...
```

`CITY` and `COUNTRY` could be environment variables defined in .env file.

```bash
CITY=NYC
COUNTRY=USA
```

**Describe alternatives you've considered**
The user could use the CLI to manually set up default params, but it is not as neat as defining them in manifest.

**Additional context**
This is extremely useful for the cases when developers need to share variables across multiple actions.
