### ISSUE TITLE
Updating alarms feed params does not change scheduled trigger execution

### ISSUE THREAD

**Issue by duynguyen** [adobe/aio-cli-plugin-runtime#205]
In the manifest.yml file, you can specify schedule cron jobs with trigger feeds and rules.

```yaml
actions:
    import-users:
      function: actions/import-user/index.js
      runtime: 'nodejs:12'
triggers:
  sync-users:
    feed: /whisk.system/alarms/interval
    inputs: 
      minutes: 1
rules:
  sync-users-rule:
    trigger: sync-users
    action: import-users
```

After that you might want to update the interval to be 3 minutes instead of 1. Then `aio app deploy`. After redeployed you can check the info of `sync-users` trigger. It shows 3 minutes correctly.

```bash
{
  "annotations": [
    {
      "key": "whisk-managed",
      "value": {
        ...
      }
    },
    {
      "key": "feed",
      "value": "/whisk.system/alarms/interval"
    }
  ],
  "limits": {},
  "name": "sync-users",
  "namespace": "my-namespace",
  "parameters": [
    {
      "key": "minutes",
      "value": 3
    }
  ],
  "publish": false,
  "rules": {
    "my-namespace/sync-users-rule": {
      "action": {
        "name": "import-users",
        "path": "my-namespace/test-app-alarms-0.0.1"
      },
      "status": "active"
    }
  },
  "updated": 1605187489818,
  "version": "0.0.6"
}
```

However the trigger is still fired every minute, like it was never updated.

This could be an issue with the alarms package itself, but creating this ticket for triaging purpose.
