### ISSUE TITLE
$envvar replacement not fully supported

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-runtime#251]
It looks like the env var replacement of manifest.yml keys is not fully supported.

This example from the openwhisk docs does not seem to work.

```yml
actions:
      hello_world_env_var_parms:
        function: src/hello.js
        inputs:
          name: $FIRSTNAME
          place: ${TOWN}, ${COUNTRY}
```
FIRSTNAME  is replaced, but TOWN and COUNTRY are not.

https://github.com/apache/openwhisk-wskdeploy/blob/master/docs/wskdeploy_action_env_var_parms.md#actions
