### ISSUE TITLE
cosmetic issue: `route list basepath` in aio-cli is not returning the same value when using `wsk` cli

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-runtime#287]
Note the difference in the `API Name` column.

app.config.yaml:
```
application:
  actions: actions
  runtimeManifest:
    packages:
      my-app:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
        apis:
          my-api:
            get:
              data:
                generic:
                  method: get
```

aio-cli:
```
❯ aio runtime route list get
 Action                                   Verb      API Name  Url
 ──────────────────────────────────────── ─────────  
/53444-shazff8-stage/my-app/generic.json get       /get      https://adobeioruntime.net/apis/53444-shazff8-stage/get/data
```

wsk cli:
```
❯ WSK_CONFIG_FILE=.wskprops wsk api list get
ok: APIs
Action                                      Verb  API Name  URL
/53444-shazff8-stage/my-app/generic.json     get    my-api  https://adobeioruntime.net/apis/53444-shazff8-stage/get/data
```
